# Generated by Django 4.1.6 on 2023-02-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
        ('base', '0003_user_avatar'),
    ]

    operations = [
    ]
